### ISSUE TITLE
TF_CLOUD: Add carbon neutral 

### ISSUE THREAD

**Issue by Sacha96** [threefoldfoundation/www_threefold_cloud#24]
Create block that covers carbon neutral approach:

Title: First Carbon Neutral Cloud

Text: 

ThreeFold’s peer-to-peer nature brings considerable energy efficiencies as compared to current solutions. 

The remaining carbon footprint of the grid will be converted into carbon credits and invested in planet positive projects to enable the world’s first carbon neutral cloud.

**Comment by Vilnite** [comment]
https://docs.google.com/presentation/d/1tRPjubgQaspXIXFV1vh8eiyBGrXAW6yuIeZbMN7a9qA/edit#slide=id.gc6f21bb149_0_0

**Comment by Vilnite** [comment]
Best to create a wiki page that has all the details and facts backing this claim and then we can bring a block on each relevant website linking to this wiki page.

**Comment by Sacha96** [comment]
![CLOUD - Earth Friendly Block](https://user-images.githubusercontent.com/54844940/115037051-5b786300-9ece-11eb-82ca-b92f59e7d708.png)

**Comment by Sacha96** [comment]
Add above pricing section. Will create wiki and we can link by sunday.

**Comment by Vilnite** [comment]
I'm sure you meant Carbon Neutral section instead of Pricing.

So I'm adding this to threefold_io:
<img width="478" alt="Screenshot 2021-04-16 at 18 29 03" src="https://user-images.githubusercontent.com/20182572/115055406-0e09ef00-9eea-11eb-81f1-16634d4a06f3.png">


And this to farming:
<img width="640" alt="Screenshot 2021-04-16 at 18 29 13" src="https://user-images.githubusercontent.com/20182572/115055421-12cea300-9eea-11eb-8247-8aca234fe621.png">

Both on home pages.

Will add button when we have wiki to link to.

**Comment by Vilnite** [comment]
I'm sure you meant Carbon Neutral section instead of Pricing.

So I'm adding this to cloud:
<img width="478" alt="Screenshot 2021-04-16 at 18 29 03" src="https://user-images.githubusercontent.com/20182572/115055406-0e09ef00-9eea-11eb-81f1-16634d4a06f3.png">


And this to farming:
<img width="640" alt="Screenshot 2021-04-16 at 18 29 13" src="https://user-images.githubusercontent.com/20182572/115055421-12cea300-9eea-11eb-8247-8aca234fe621.png">

Both on home pages. I'll just apply my best judgement to where exactly position it. Please lmk if any corrections required.

Will add button when we have wiki page to link to.
